-- return {
--     "nvim-neo-tree/neo-tree.nvim",
--     branch = "v3.x",
--     dependencies = {
--         "nvim-lua/plenary.nvim",
--         "nvim-tree/nvim-web-devicons",
--         "MunifTanjim/nui.nvim",
--         "3rd/image.nvim",
--     },
--     opts = {
--         window = {
--             position = "left",
--             width = 30,
--             mapping_options = {
--                 noremap = true,
--                 nowait = true,
--             },
--             mappings = {
--                 ["<space>"] = {
--                     "toggle_node",
--                     nowait = false,
--                 },
--                 ["P"] = { "toggle_preview", config = { use_image_nvim = true } },
--             },
--             preview_width = 50,
--             preview = true,
--         },
--         filesystem = {
--             follow_current_file = {
--                 enabled = true,
--             },
--             group_empty_dirs = false,
--             hijack_netrw_behavior = "open_default",
--             use_libuv_file_watcher = true,
--             window = {
--                 mappings = {
--                     ["<bs>"] = "navigate_up",
--                     ["."] = "set_root",
--                     ["H"] = "toggle_hidden",
--                     ["/"] = "fuzzy_finder",
--                     ["D"] = "fuzzy_finder_directory",
--                     ["f"] = "filter_on_submit",
--                     ["<c-x>"] = "clear_filter",
--                     ["[g"] = "prev_git_modified",
--                     ["]g"] = "next_git_modified",
--                 }
--             }
--         },
--     }
-- }
